{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Extract_1\",\"Extract\",\"_Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "d8f68101-d61a-4ceb-adb8-1245f2a99b16",
        "fromColumn": "Est_IHD",
        "fromTable": "Extract_1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_733e3aeb-49ed-4803-b3d6-3ff1b5f1fa76"
      },
      {
        "name": "9ddd61b5-7cf1-4268-b03f-fd81587628ca",
        "fromColumn": "Est IHD (copy)",
        "fromTable": "Extract_1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_39312de2-7a2b-47d3-9374-89a175986186"
      },
      {
        "name": "cd60ecb2-f199-4aac-bd6d-0083774b4f90",
        "fromColumn": "EST_IHD",
        "fromTable": "Extract",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_10a12dba-9d3a-446a-b254-a5797d834c22"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Extract_1",
        "columns": [
          {
            "name": "Ad_Group1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8a8048a-ef89-4398-a93a-c86f88b4b241",
            "sourceColumn": "Ad_Group1",
            "summarizeBy": "none"
          },
          {
            "name": "Dealer Name(match)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70312820-5475-47ad-8858-98399b8dac97",
            "sourceColumn": "Dealer Name(match)",
            "summarizeBy": "none"
          },
          {
            "name": "Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "85ecd7ee-a2b7-4fdf-a6bc-b7f151a0cbdd",
            "sourceColumn": "Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Est_IHD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "lineageTag": "828345a0-b5d7-408d-9a3b-decbdfa36406",
            "sourceColumn": "Est_IHD",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_733e3aeb-49ed-4803-b3d6-3ff1b5f1fa76"
                },
                "isDefault": true,
                "relationship": "d8f68101-d61a-4ceb-adb8-1245f2a99b16"
              }
            ]
          },
          {
            "name": "Total_Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "50ff2016-1924-4e43-98af-7f28d7f5858c",
            "sourceColumn": "Total_Calls",
            "summarizeBy": "sum"
          },
          {
            "name": "Retailer_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f5c9acb2-b691-46ac-9735-1f3a2f2599b4",
            "sourceColumn": "Retailer_Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Extract_1'[Est_IHD])",
            "lineageTag": "3485f0a6-91ee-4c17-a122-cbcb97254a14",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Date Range",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "VAR StartDate = DATEVALUE(SELECTEDVALUE('Start Date (copy 2)'[Value])) VAR EndDate = DATEVALUE(SELECTEDVALUE('Start Date_1 (copy)'[Value])) RETURN 'Extract_1'[Est_IHD] >= StartDate && 'Extract_1'[Est_IHD] <= EndDate",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9cb1beb1-466b-497c-9602-19530e48f456",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Extract_1'[Est_IHD], \"mmm\")",
            "lineageTag": "39057d7b-51c8-4f25-9052-54e0783be6e2",
            "sortByColumn": "Month Number",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Monthly / Weekly View/BDN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR SelectedView = SELECTEDVALUE('Cost Per Call Parameter'[Value]) ",
              "VAR TheDate = 'Extract_1'[Est_IHD] ",
              "VAR TheYear = YEAR(TheDate) ",
              "VAR TheQuarter = QUARTER(TheDate) ",
              "VAR TheWeek = WEEKNUM(TheDate, 2) ",
              "VAR TheMonth = FORMAT(TheDate, \"mmm\") ",
              "RETURN ",
              "SWITCH(SelectedView, \"QQ\", \"Q\" & TheQuarter & \"'\" & RIGHT(TheYear, 2), \"WW\", \"Wk \" & TheWeek & \"'\" & RIGHT(TheYear, 2), \"MM\", TheMonth & \"'\" & RIGHT(TheYear, 2))",
              ""
            ],
            "lineageTag": "97895053-d20a-48bc-9280-3320a3d92e5e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "cpd_mon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "VAR MaxDateOverall = CALCULATE(MAX('Extract_1'[Est_IHD]), ALL('Extract_1')) VAR CurrentMonthMarker = EOMONTH(MaxDateOverall, 0) VAR PreviousMonthMarker = EOMONTH(MaxDateOverall, -1) VAR RowMonthMarker = EOMONTH('Extract_1'[Est_IHD], 0) RETURN SWITCH(TRUE(), RowMonthMarker = CurrentMonthMarker, \"Current\", RowMonthMarker = PreviousMonthMarker, \"Previous\", BLANK())",
            "lineageTag": "0991fa10-2a68-460e-8a4c-ba400753411b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Est IHD (copy)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "'Extract_1'[Est_IHD]",
            "lineageTag": "b1f75b4a-6911-48d1-bb47-91dcbb25e623",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_39312de2-7a2b-47d3-9374-89a175986186"
                },
                "isDefault": true,
                "relationship": "9ddd61b5-7cf1-4268-b03f-fd81587628ca"
              }
            ]
          },
          {
            "name": "Month_end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Extract_1'[Est_IHD]) * 100 + MONTH('Extract_1'[Est_IHD])",
            "lineageTag": "e8e1a63a-8fe5-4cae-be14-56574960effe",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month_strt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Extract_1'[Est_IHD]) * 100 + MONTH('Extract_1'[Est_IHD])",
            "lineageTag": "a6cbe7a7-eed6-44e9-a659-c49d2c2ba6b6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Mon_yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Extract_1'[Est_IHD], \"MMM\") & \" - \" & RIGHT(FORMAT('Extract_1'[Year], \"0\"), 2)",
            "lineageTag": "b497bfd3-053e-422e-b8a1-cb560fb1828a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Color Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(YEAR('Extract_1'[Est_IHD]), \"0\") & \"-\" & 'Extract_1'[Mail Type (copy)]",
            "lineageTag": "92cc10af-7a38-4a47-b4ed-281f57939a3a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Qtr_yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"Q\" & FORMAT(QUARTER('Extract_1'[Est_IHD]), \"0\") & \"-\" & RIGHT(FORMAT('Extract_1'[Year], \"0\"), 2)",
            "lineageTag": "3e148852-8243-4cf3-80ab-72bb8291b19b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Color Code (copy)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(YEAR('Extract_1'[Est_IHD]), \"0\") & \"-\" & 'Extract_1'[Mail Type (copy)]",
            "lineageTag": "bd64d39f-4df2-4c43-8511-7628d8857591",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mail Type (copy)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE(),",
              "    Extract_1[Ad_Group1] = \"BULK\", \"Branded-Saturation\",",
              "    Extract_1[Ad_Group1] = \"GENERIC\", \"Generic-Saturation\",",
              "    Extract_1[Ad_Group1] = \"EDDM\", \"EDDM\",",
              "    Extract_1[Ad_Group1] = \"RADIUS\", \"Radius\",",
              "    BLANK()",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6d5b3ba6-954b-4225-938a-3735e58e2789",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week_yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "\"Week \" & WEEKNUM('Extract_1'[Est_IHD],2)",
            "isDataTypeInferred": true,
            "lineageTag": "e63609a7-af76-407a-bc5f-4362ea9e4712",
            "sortByColumn": "Week Sort",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM ( Extract_1[Est_IHD], 2 )",
            "isDataTypeInferred": true,
            "lineageTag": "20f636aa-fd3c-4c10-93c9-f18b04493d8f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH ( 'Extract_1'[Est_IHD] )",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7fa3d4fe-d677-470e-997f-f830ab2cc9d1",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "48f77322-8082-4ef9-bcd2-074129588878",
        "partitions": [
          {
            "name": "Extract_1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Raj244639\\Documents\\tableau-powerbi\\updated_backend\\tab2pbi\\ddm\\data\\Extract_1.csv\"),[Delimiter=\",\", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Ad_Group1\", type text}, {\"Dealer Name(match)\", type text}, {\"Count\", Int64.Type}, {\"Est_IHD\", type datetime}, {\"Total_Calls\", Int64.Type}, {\"Retailer_Cost\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Extract",
        "columns": [
          {
            "name": "SRC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fd916ef-b770-453a-9d87-c55f878d532a",
            "sourceColumn": "SRC",
            "summarizeBy": "none"
          },
          {
            "name": "EST_IHD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c47c8f61-2126-4ffc-89fd-cbdb360f360f",
            "sourceColumn": "EST_IHD",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_10a12dba-9d3a-446a-b254-a5797d834c22"
                },
                "isDefault": true,
                "relationship": "cd60ecb2-f199-4aac-bd6d-0083774b4f90"
              }
            ]
          },
          {
            "name": "Dealer Name (matched)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7b9a895-5b6c-4d1b-95d7-0f484f7d9d5f",
            "sourceColumn": "Dealer Name (matched)",
            "summarizeBy": "none"
          },
          {
            "name": "MailQTY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "a52c048c-b208-40a0-bc5a-f58c8b896e3f",
            "sourceColumn": "MailQTY",
            "summarizeBy": "sum"
          },
          {
            "name": "DealerOrders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "5ef34645-b3d0-45e7-9db6-7c1a7baeebd7",
            "sourceColumn": "DealerOrders",
            "summarizeBy": "sum"
          },
          {
            "name": "DealerActivations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "a5830b7b-ae48-4319-b5ef-9d6be5fbcb6f",
            "sourceColumn": "DealerActivations",
            "summarizeBy": "sum"
          },
          {
            "name": "Beam_Status_Pre_P1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf638938-1f6b-46c2-883c-efb4e00f3b8b",
            "sourceColumn": "Beam_Status_Pre_P1",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca52964b-d94d-41c1-8d28-4c68887b4c07",
            "sourceColumn": "Beam_Status_P1",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecac1308-9977-4293-9492-574787dc5e9e",
            "sourceColumn": "Beam_Status_P2",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb2ce27c-7771-4bfa-90ac-e64da5ce1023",
            "sourceColumn": "Beam_Status_P3",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c453519c-7f05-4c41-acf6-a2a7a38ff4fd",
            "sourceColumn": "Beam_Status_P4",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15c3000b-850b-4a71-aa1a-7086a9aeac8f",
            "sourceColumn": "Beam_Status_P5",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2133bc9-5264-4dc7-bd09-ac072e524d8a",
            "sourceColumn": "Beam_Status_P6",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05a7f3b6-0a0f-435f-a6b9-c5ed154ac222",
            "sourceColumn": "Beam_Status_P7",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7faf7e67-cfe1-4c3b-bb22-cf37847c763e",
            "sourceColumn": "Beam_Status_P8",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_P9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0ac99bf-c46b-4686-8cb5-543ddc0240ff",
            "sourceColumn": "Beam_Status_P9",
            "summarizeBy": "none"
          },
          {
            "name": "Beam_Status_Today",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Extract'[Beam_Status_P9]",
            "lineageTag": "bb0b1335-3c93-4a40-8ff9-90fde0157ef8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Extract'[EST_IHD])",
            "lineageTag": "34cbe113-7f8a-47a6-9996-0db605c8f1e6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Mail Type Aliased",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH('Extract'[SRC], \"Branded\", \"Branded-Saturation\", \"Branded Radius\", \"Radius\", \"DealerRadius\", \"Radius\", \"Generic\", \"Generic-Saturation\")",
            "lineageTag": "5f2b4d58-eea4-42cd-9bca-5410c3f8116c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date Range",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "VAR StartDate = DATEVALUE(SELECTEDVALUE('Start Date (copy 2)'[Value])) VAR EndDate = DATEVALUE(SELECTEDVALUE('Start Date_1 (copy)'[Value])) RETURN 'Extract'[EST_IHD] >= StartDate && 'Extract'[EST_IHD] <= EndDate",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "95d80b76-3561-4b04-acdb-c571ce38ea75",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Extract'[EST_IHD], \"mmm\")",
            "lineageTag": "d3a77ee4-9e69-4971-a50e-58489ee1178a",
            "sortByColumn": "Month Number",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Test_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Extract'[EST_IHD] < DATE(2016, 1, 1), \"Pre 2010\", \"Test Not\")",
            "lineageTag": "93544d0e-6203-4602-b49e-c6c9a05261d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MOY_Merge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Extract'[EST_IHD]) * 100 + MONTH('Extract'[EST_IHD])",
            "lineageTag": "cf168e8d-0341-4e54-b0f6-39db9c0ee410",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Beam_Status_At_Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "VAR TheDate = 'Extract'[EST_IHD] RETURN SWITCH(TRUE(), TheDate < DATE(2018, 1, 4), 'Extract'[Beam_Status_Pre_P1], TheDate < DATE(2018, 4, 5), 'Extract'[Beam_Status_P1], TheDate < DATE(2018, 5, 31), 'Extract'[Beam_Status_P2], TheDate < DATE(2018, 8, 2), 'Extract'[Beam_Status_P3], TheDate < DATE(2018, 9, 27), 'Extract'[Beam_Status_P4], TheDate < DATE(2019, 1, 3), 'Extract'[Beam_Status_P5], TheDate < DATE(2019, 2, 14), 'Extract'[Beam_Status_P6], TheDate < DATE(2019, 3, 28), 'Extract'[Beam_Status_P7], TheDate < DATE(2019, 6, 27), 'Extract'[Beam_Status_P8], 'Extract'[Beam_Status_P9])",
            "lineageTag": "e7d7119e-3932-4795-94f5-bc2133db8ef0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Monthly / Weekly View",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "VAR SelectedView = SELECTEDVALUE('Cost Per Call Parameter'[Value]) VAR TheDate = 'Extract'[EST_IHD] RETURN SWITCH(SelectedView, \"QQ\", \"Q\" & QUARTER(TheDate), \"WW\", \"Week \" & WEEKNUM(TheDate, 2), \"MM\", FORMAT(TheDate, \"mmm\"))",
            "lineageTag": "2a447119-7149-46c3-a911-955009be4be6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Monthly / Weekly View /BDN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "VAR SelectedView = SELECTEDVALUE('Cost Per Call Parameter'[Value]) VAR TheDate = 'Extract'[EST_IHD] VAR TheYear = YEAR(TheDate) VAR TheQuarter = QUARTER(TheDate) VAR TheWeek = WEEKNUM(TheDate, 2) VAR TheMonth = FORMAT(TheDate, \"mmm\") RETURN SWITCH(SelectedView, \"QQ\", \"Q\" & TheQuarter & \"'\" & RIGHT(TheYear, 2), \"WW\", \"Wk \" & TheWeek & \"'\" & RIGHT(TheYear, 2), \"MM\", TheMonth & \"'\" & RIGHT(TheYear, 2))",
            "lineageTag": "58133188-4e41-4c72-800c-e0e57c78f27c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mon_yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Extract'[EST_IHD], \"MMM\") & \" - \" & RIGHT(FORMAT('Extract'[Year], \"0\"), 2)",
            "lineageTag": "5947969f-cda2-4e00-a8df-9a72b24d2bf6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BST_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH(TRUE(), 'Extract'[Beam_Status_Today] = \"GROWTH\", \"GROWTH\", 'Extract'[Beam_Status_Today] = \"STANDARD\", \"STANDARD\", 'Extract'[Beam_Status_Today] = \"MANAGED\", \"MANAGED\", 'Extract'[Beam_Status_Today] = \"NO J2\", \"STANDARD\", ISBLANK('Extract'[Beam_Status_Today]), \"EXCLUDE\", 'Extract'[Beam_Status_Today] = \"PR\", \"EXCLUDE\", 'Extract'[Beam_Status_Today] = \"-\", \"EXCLUDE\", BLANK())",
            "lineageTag": "4cae9f8b-27b1-4bfe-9b49-4f085b59fdbb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BSAT_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH(TRUE(), 'Extract'[Beam_Status_At_Time] = \"GROWTH\", \"GROWTH\", 'Extract'[Beam_Status_At_Time] = \"STANDARD\", \"STANDARD\", 'Extract'[Beam_Status_At_Time] = \"MANAGED\", \"MANAGED\", 'Extract'[Beam_Status_At_Time] = \"NO J2\", \"STANDARD\", ISBLANK('Extract'[Beam_Status_At_Time]), \"EXCLUDE\", 'Extract'[Beam_Status_At_Time] = \"PR\", \"EXCLUDE\", 'Extract'[Beam_Status_At_Time] = \"-\", \"EXCLUDE\", BLANK())",
            "lineageTag": "6bde0352-4a37-4180-ac7f-d26fcb6e1621",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Color Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(YEAR('Extract'[EST_IHD]), \"0\") & \"-\" & 'Extract'[Mail Type Aliased]",
            "lineageTag": "be08b66b-cea7-4c21-ad17-369cad68e5a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week_yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "\"Week \" & WEEKNUM('Extract'[EST_IHD],2)",
            "isDataTypeInferred": true,
            "lineageTag": "64340edc-cd72-41fe-b414-c1be837f80f6",
            "sortByColumn": "Week Sort",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Qtr_yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"Q\" & FORMAT(QUARTER('Extract'[EST_IHD]), \"0\") & \"-\" & RIGHT(FORMAT('Extract'[Year], \"0\"), 2)",
            "isDataTypeInferred": true,
            "lineageTag": "0f893ffc-a286-4782-ac47-8276b2a62ddd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM ( 'Extract'[EST_IHD], 2 )",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a8ef1256-63b2-41c6-ae3f-ad91acc2f123",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH ( 'Extract'[EST_IHD] )",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "41efe2a4-bdbf-4075-871f-657d7fa1c3e2",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d3974d9f-93a1-4280-845b-8cad529ed18e",
        "partitions": [
          {
            "name": "Extract",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Raj244639\\Documents\\tableau-powerbi\\updated_backend\\tab2pbi\\ddm\\data\\Extract.csv\"),[Delimiter=\",\", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SRC\", type text}, {\"EST_IHD\", type datetime}, {\"Dealer Name (matched)\", type text}, {\"MailQTY\", Int64.Type}, {\"DealerOrders\", Int64.Type}, {\"DealerActivations\", Int64.Type}, {\"Beam_Status_Pre_P1\", type text}, {\"Beam_Status_P1\", type text}, {\"Beam_Status_P2\", type text}, {\"Beam_Status_P3\", type text}, {\"Beam_Status_P4\", type text}, {\"Beam_Status_P5\", type text}, {\"Beam_Status_P6\", type text}, {\"Beam_Status_P7\", type text}, {\"Beam_Status_P8\", type text}, {\"Beam_Status_P9\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Cost Per Call Parameter",
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ad8d4c03-f7bb-4726-9871-c0266457b7a4",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "709f4353-03c4-4147-8afe-efd47bd038c0",
            "sourceColumn": "[Display]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "99893427-9e51-4927-890f-1fa133e877a8",
        "partitions": [
          {
            "name": "Cost Per Call Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Value\", STRING,",
                "    \"Display\", STRING,",
                "    {",
                "        { \"QQ\", \"Quarterly\" },",
                "        { \"MM\", \"Monthly\" },",
                "        { \"WW\", \"Weekly\" }",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "KPI List (copy)",
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1614f8fb-e3d3-4a66-bdc9-9d26753b6f09",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "396bd95b-ccda-4b76-bb84-0b09147768d9",
            "sourceColumn": "[Display]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1837b0fa-22e9-427a-9c95-e2f8f5f2447c",
        "partitions": [
          {
            "name": "KPI List (copy)",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Value\", STRING,",
                "    \"Display\", STRING,",
                "    {",
                "        { \"MQ\", \"Mail Quantity\" },",
                "        { \"DO\", \"Dealer Orders\" },",
                "        { \"DA\", \"Dealer Activations\" },",
                "        { \"OR\", \"Order Rate\" },",
                "        { \"AR\", \"Activations Rate\" },",
                "        { \"CPDO\", \"Cost Per Dealer Order\" }",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "KPI List 2 (copy)",
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "895a1d96-220b-4f67-ae71-a6486cf9174f",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "15d8bee3-4191-48b8-aaa8-517d9ba43e22",
            "sourceColumn": "[Display]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6a5328f8-61c0-401b-aeb5-f3ca81a04056",
        "partitions": [
          {
            "name": "KPI List 2 (copy)",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Value\", STRING,",
                "    \"Display\", STRING,",
                "    {",
                "        { \"CPDO\", \"Cost Per Dealer Order\" },",
                "        { \"CPDA\", \"Cost Per Dealer Activation\" },",
                "        { \"HCPDO\", \"Hughes Cost Per Dealer Order\" },",
                "        { \"DCPDO\", \"Dealer Cost Per Dealer Order\" },",
                "        { \"SAC\", \"SAC\" }",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Monthly / Weekly View  (copy 2)",
        "columns": [
          {
            "name": "Monthly / Weekly View  (copy 2)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6dd507c7-8a2d-492c-b8ae-5d6857f84316",
            "sourceColumn": "[Monthly / Weekly View  (copy 2)]",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3ea0ead1-4bbc-4e66-9dcb-59e9597f4ec2",
        "partitions": [
          {
            "name": "Monthly / Weekly View  (copy 2)",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Monthly / Weekly View  (copy 2)\", STRING,",
                "    {",
                "        { \"YR\" },",
                "        { \"MT\" }",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Monthly / Weekly View  (copy)",
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c51e3ac3-66e2-40a8-94b2-d8a81d10badc",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d6578268-fef8-4785-a637-f5c343181671",
            "sourceColumn": "[Display]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "99a14532-3aff-435c-914f-be4dcecf8c3d",
        "partitions": [
          {
            "name": "Monthly / Weekly View  (copy)",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Value\", STRING,",
                "    \"Display\", STRING,",
                "    {",
                "        { \"CNT\", \"Mail Quantity\" },",
                "        { \"TC\", \"Total Calls\" },",
                "        { \"CPC\", \"Cost Per Call\" },",
                "        { \"RR\", \"Response Rate\" }",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Start Date (copy 2)",
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c65fbb4c-9d42-46c6-9489-652c1019a9f7",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9fbb7c74-6389-459c-a236-20a737552c29",
            "sourceColumn": "[Display]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2d603e5d-1c53-453b-b22e-62aadedab11e",
        "partitions": [
          {
            "name": "Start Date (copy 2)",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Value\", STRING,",
                "    \"Display\", STRING,",
                "    {    ",
                "        { \"2017-01-31\", \"Jan-17\" },",
                "        { \"2017-02-28\", \"Feb-17\" },",
                "        { \"2017-03-31\", \"Mar-17\" },",
                "        { \"2017-04-30\", \"Apr-17\" },",
                "        { \"2017-05-31\", \"May-17\" },",
                "        { \"2017-06-30\", \"Jun-17\" },",
                "        { \"2017-07-31\", \"Jul-17\" },",
                "        { \"2017-08-31\", \"Aug-17\" },",
                "        { \"2017-09-30\", \"Sep-17\" },",
                "        { \"2017-10-31\", \"Oct-17\" },",
                "        { \"2017-11-30\", \"Nov-17\" },",
                "        { \"2017-12-31\", \"Dec-17\" },",
                "",
                "        { \"2018-01-31\", \"Jan-18\" },",
                "        { \"2018-02-28\", \"Feb-18\" },",
                "        { \"2018-03-31\", \"Mar-18\" },",
                "        { \"2018-04-30\", \"Apr-18\" },",
                "        { \"2018-05-31\", \"May-18\" },",
                "        { \"2018-06-30\", \"Jun-18\" },",
                "        { \"2018-07-31\", \"Jul-18\" },",
                "        { \"2018-08-31\", \"Aug-18\" },",
                "        { \"2018-09-30\", \"Sep-18\" },",
                "        { \"2018-10-31\", \"Oct-18\" },",
                "        { \"2018-11-30\", \"Nov-18\" },",
                "        { \"2018-12-31\", \"Dec-18\" },",
                "",
                "        { \"2019-01-31\", \"Jan-19\" },",
                "        { \"2019-02-28\", \"Feb-19\" },",
                "        { \"2019-03-31\", \"Mar-19\" },",
                "        { \"2019-04-30\", \"Apr-19\" },",
                "        { \"2019-05-31\", \"May-19\" },",
                "        { \"2019-06-30\", \"Jun-19\" },",
                "        { \"2019-07-31\", \"Jul-19\" },",
                "        { \"2019-08-31\", \"Aug-19\" }",
                "",
                "",
                "    }",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Start Date_1 (copy)",
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "53c1c4b9-81d4-4d79-812f-3f69b66a0701",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "05375ac6-4f84-49d7-9e3f-9eb884399bcc",
            "sourceColumn": "[Display]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "817806ca-52a8-4363-8c67-dc2a4da000bf",
        "partitions": [
          {
            "name": "Start Date_1 (copy)",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Value\", STRING,",
                "    \"Display\", STRING,",
                "    {",
                "        { \"2017-01-31\", \"Jan-17\" },",
                "        { \"2017-02-28\", \"Feb-17\" },",
                "        { \"2017-03-31\", \"Mar-17\" },",
                "        { \"2017-04-30\", \"Apr-17\" },",
                "        { \"2017-05-31\", \"May-17\" },",
                "        { \"2017-06-30\", \"Jun-17\" },",
                "        { \"2017-07-31\", \"Jul-17\" },",
                "        { \"2017-08-31\", \"Aug-17\" },",
                "        { \"2017-09-30\", \"Sep-17\" },",
                "        { \"2017-10-31\", \"Oct-17\" },",
                "        { \"2017-11-30\", \"Nov-17\" },",
                "        { \"2017-12-31\", \"Dec-17\" },",
                "",
                "        { \"2018-01-31\", \"Jan-18\" },",
                "        { \"2018-02-28\", \"Feb-18\" },",
                "        { \"2018-03-31\", \"Mar-18\" },",
                "        { \"2018-04-30\", \"Apr-18\" },",
                "        { \"2018-05-31\", \"May-18\" },",
                "        { \"2018-06-30\", \"Jun-18\" },",
                "        { \"2018-07-31\", \"Jul-18\" },",
                "        { \"2018-08-31\", \"Aug-18\" },",
                "        { \"2018-09-30\", \"Sep-18\" },",
                "        { \"2018-10-31\", \"Oct-18\" },",
                "        { \"2018-11-30\", \"Nov-18\" },",
                "        { \"2018-12-31\", \"Dec-18\" },",
                "",
                "        { \"2019-01-31\", \"Jan-19\" },",
                "        { \"2019-02-28\", \"Feb-19\" },",
                "        { \"2019-03-31\", \"Mar-19\" },",
                "        { \"2019-04-30\", \"Apr-19\" },",
                "        { \"2019-05-31\", \"May-19\" },",
                "        { \"2019-06-30\", \"Jun-19\" },",
                "        { \"2019-07-31\", \"Jul-19\" },",
                "        { \"2019-08-31\", \"Aug-19\" }",
                "",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_Dummy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b90a0881-3dd6-4e00-ae4f-feebc6448e1f",
            "sourceColumn": "_Dummy",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f2e13123-4219-4c98-b1df-b6b002dde174",
        "measures": [
          {
            "name": "Home",
            "expression": "\"Home\"",
            "lineageTag": "16bce52c-359f-4f6b-80a0-0f729e9668e8"
          },
          {
            "name": "TWG",
            "expression": "\"TWG Dashboard\"",
            "lineageTag": "5fb07fef-cc43-4304-9e3c-5adf389fdbbc"
          },
          {
            "name": "Matchback Navigation 1",
            "expression": "\"Matchback Dashboard 1\"",
            "lineageTag": "eafc4e1b-3904-46dd-9211-6ec284ee21cd"
          },
          {
            "name": "Matchback Navigation 2",
            "expression": "\"Matchback Dashboard 2\"",
            "lineageTag": "7287a1c2-53f0-4c3f-acd4-b8eb4f0d81aa"
          },
          {
            "name": "DA_LKP",
            "expression": "\"Not convertible: Tableau's LOOKUP function is context-dependent and has no direct DAX equivalent.\"",
            "lineageTag": "6fd0a70d-e280-4291-abc5-d55b0e14b325"
          },
          {
            "name": "Cost per Call",
            "expression": "DIVIDE(SUM('Extract_1'[Retailer_Cost]), SUM('Extract_1'[Total_Calls]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6e682fbb-1efb-4ef8-b16d-9d5505d1f5b3"
          },
          {
            "name": "Resp. Rate",
            "expression": "DIVIDE(SUM('Extract_1'[Total_Calls]), SUM('Extract_1'[Count]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "92a8b244-bd71-4a28-8a29-1e5a3c6ec58d"
          },
          {
            "name": "Activation Rate",
            "expression": "DIVIDE(SUM('Extract'[DealerActivations]), SUM('Extract'[DealerOrders]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "21a8ac2c-1f7d-45a1-8393-28b73f9277bd"
          },
          {
            "name": "Cost per Dealer Activation",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "0.45 * DIVIDE(SUM('Extract'[MailQTY]), SUM('Extract'[DealerActivations]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1358c1bd-7f93-4934-b603-b04e671d0bec"
          },
          {
            "name": "Cost per Dealer Order",
            "expression": "0.45 * DIVIDE(SUM('Extract'[MailQTY]), SUM('Extract'[DealerOrders]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d9c67f35-8e5a-47e8-a909-9fd7eb146cb9"
          },
          {
            "name": "Order Rate",
            "expression": "DIVIDE(SUM('Extract'[DealerOrders]), SUM('Extract'[MailQTY]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "28314829-cf08-4c2c-8ffd-ede1bf4ac60a"
          },
          {
            "name": "Call",
            "expression": "\"Call\"",
            "lineageTag": "d2d3c05e-c6c3-4b77-a8f4-9f62f332e25b"
          },
          {
            "name": "Order",
            "expression": "\"Order\"",
            "lineageTag": "b15954a9-c4af-4409-8347-b2105fee676b"
          },
          {
            "name": "MB",
            "expression": "\"MB1 Dashboard\"",
            "lineageTag": "f2752b78-3a19-42d0-ba39-8027d38c508e"
          },
          {
            "name": "CAlc_0",
            "expression": "0",
            "lineageTag": "db3f70ce-4190-4a20-a4f6-87ee7bcdb3a6"
          },
          {
            "name": "DO_LKP",
            "expression": "\"Not convertible: Tableau's LOOKUP function is context-dependent and has no direct DAX equivalent.\"",
            "lineageTag": "00e70d2b-baaa-480f-b3b2-3ae6e2606ca1"
          },
          {
            "name": "Mail",
            "expression": "\"Mail\"",
            "lineageTag": "ed6b6dca-7a0e-44ae-8508-f299ccc867f5"
          },
          {
            "name": "MQ_LKP",
            "expression": "\"Not convertible: Tableau's LOOKUP function is context-dependent and has no direct DAX equivalent.\"",
            "lineageTag": "09bc7e97-5d3f-44e9-961c-2e4e3a8e1ce2"
          },
          {
            "name": "Cost per 1000 Pieces",
            "expression": "DIVIDE(SUM('Extract_1'[Retailer_Cost]), SUM('Extract_1'[Count]))",
            "lineageTag": "f3fbe20c-0431-4784-aa0a-6eb8ec9cea40"
          },
          {
            "name": "KPI 1",
            "expression": "SELECTEDVALUE('Monthly / Weekly View  (copy)'[Value])",
            "lineageTag": "e0b69361-2046-4ee2-90f4-7afa73f00d69"
          },
          {
            "name": "Zero",
            "expression": "0",
            "lineageTag": "5a2299d4-28ae-4562-9613-33fcdd5e44a2"
          },
          {
            "name": "Mail Qty_Str",
            "expression": "\"Mail Qty\"",
            "lineageTag": "a5a7e613-07c3-4458-8edd-3e9e7488c3f6"
          },
          {
            "name": "test",
            "expression": "MAX('Extract_1'[Est_IHD])",
            "lineageTag": "7ed04fe7-07fd-4826-970b-a2ea9f6df220"
          },
          {
            "name": "Month",
            "expression": "MONTH(SELECTEDVALUE('Extract_1'[Est_IHD]))",
            "lineageTag": "98467bf3-c56b-4cab-9fad-d288fe185d98"
          },
          {
            "name": "Quarter",
            "expression": "QUARTER(SELECTEDVALUE('Extract_1'[Est_IHD]))",
            "lineageTag": "d831deae-f6b2-41ee-a52b-d5699522bae6"
          },
          {
            "name": "Hughes",
            "expression": "\"HUGHES\"",
            "lineageTag": "5d1d24c2-89cd-412d-ba20-8789f0a04802"
          },
          {
            "name": "FA",
            "expression": "\"FA\"",
            "lineageTag": "02792087-94f2-490a-9b58-6eef4aea9014"
          },
          {
            "name": "TC_LKP",
            "expression": "\"Not convertible: Tableau's LOOKUP function is context-dependent and has no direct DAX equivalent.\"",
            "lineageTag": "a9572c1a-26e4-4720-b55f-152ba8beae55"
          },
          {
            "name": "KPI_2",
            "expression": "VAR SelectedKPI = SELECTEDVALUE('KPI List (copy)'[Value]) RETURN SWITCH(SelectedKPI, \"MQ\", SUM('Extract'[MailQTY]), \"DO\", SUM('Extract'[DealerOrders]), \"DA\", SUM('Extract'[DealerActivations]), \"OR\", DIVIDE(SUM('Extract'[DealerOrders]), SUM('Extract'[MailQTY])), \"AR\", DIVIDE(SUM('Extract'[DealerActivations]), SUM('Extract'[DealerOrders])), \"CPDO\", 0.45 * DIVIDE(SUM('Extract'[MailQTY]), SUM('Extract'[DealerOrders])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3c8b7b10-4f95-4756-ac4c-1c958f54ac7a"
          },
          {
            "name": "KPI 2",
            "expression": "SELECTEDVALUE('KPI List (copy)'[Value])",
            "lineageTag": "2f244625-67cd-4b5d-9aeb-5b11965282a3"
          },
          {
            "name": "Button",
            "expression": "\"Button\"",
            "lineageTag": "14e51b33-99a5-4a88-ba54-1e3fe2cd281f"
          },
          {
            "name": "KPI 3",
            "expression": "SELECTEDVALUE('KPI List 2 (copy)'[Value])",
            "lineageTag": "9106f828-6e4b-4da4-b9b2-7b2baf23c142"
          },
          {
            "name": "Count (copy)",
            "expression": "SUM('Extract_1'[Count])",
            "formatString": "#,0",
            "lineageTag": "f80d898b-a6fd-4f85-a4a1-673c34a8aa60"
          },
          {
            "name": "KPIs 1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "VAR SelectedKPI = SELECTEDVALUE('Monthly / Weekly View  (copy)'[Value]) RETURN SWITCH(SelectedKPI, \"CNT\", SUM('Extract_1'[Count]), \"TC\", SUM('Extract_1'[Total_Calls]), \"RR\", DIVIDE(SUM('Extract_1'[Total_Calls]), SUM('Extract_1'[Count])), \"CPC\", DIVIDE(SUM('Extract_1'[Retailer_Cost]), SUM('Extract_1'[Total_Calls])))",
            "lineageTag": "6c5f879e-d277-45c0-84a7-44b87ac11e76"
          },
          {
            "name": "Number of Records",
            "expression": "COUNTROWS('Extract')",
            "lineageTag": "65bc2069-2913-4b7c-b8ba-49aefe955893"
          },
          {
            "name": "Retailer Cost (copy)",
            "expression": "SUM('Extract_1'[Retailer_Cost])",
            "lineageTag": "34279002-3913-4172-809c-c787b4ccedc1"
          },
          {
            "name": "Comparison",
            "expression": "\"Comparison Dashboard\"",
            "lineageTag": "0b57859d-6203-43da-96b7-01a9db74fef3"
          },
          {
            "name": "OR_LKP",
            "expression": "VAR _currentValue = COALESCE('_Measures'[Order Rate], 0) VAR _nextValue = CALCULATE('_Measures'[Order Rate], PARALLELPERIOD('Extract'[EST_IHD], 1, MONTH)) RETURN IF(ISBLANK(_nextValue), BLANK(), SIGN(_currentValue - _nextValue))",
            "formatString": "0",
            "lineageTag": "a710a638-5d2c-4ed8-8de8-27c330198ccc"
          },
          {
            "name": "Dealer Cost",
            "expression": "SUMX('Extract', IF('Extract'[Mail Type Aliased] = \"Radius\", 0, 'Extract'[MailQTY] * 0.45 * 0.2))",
            "lineageTag": "df8fa641-1f6f-4e12-af92-ef0924597079"
          },
          {
            "name": "Hughes Cost",
            "expression": "SUMX('Extract', IF('Extract'[Mail Type Aliased] = \"Radius\", 'Extract'[MailQTY] * 0.45, 'Extract'[MailQTY] * 0.45 * 0.8))",
            "lineageTag": "1b0262ca-c23d-49fb-a534-eafe4ca906d8"
          },
          {
            "name": "SAC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "'_Measures'[Cost per Dealer Order] + 391",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "915be5d6-0098-4f91-86d7-f2e3b6f951d2"
          },
          {
            "name": "KPIs_1K",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "'_Measures'[KPIs 1] / 1000",
            "lineageTag": "fb02debe-7b71-4015-acdf-a4dd88514682"
          },
          {
            "name": "[KPI_2]/1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "'_Measures'[KPI_2] / 1000",
            "lineageTag": "e7fa2a8b-166a-475c-9852-2e23d36a1cd1"
          },
          {
            "name": "AR_LKP",
            "expression": "VAR _currentValue = COALESCE('_Measures'[Activation Rate], 0) VAR _nextValue = CALCULATE('_Measures'[Activation Rate], PARALLELPERIOD('Extract'[EST_IHD], 1, MONTH)) RETURN IF(ISBLANK(_nextValue), BLANK(), SIGN(_currentValue - _nextValue))",
            "formatString": "0",
            "lineageTag": "4e980a54-2b0c-44fa-85fe-8f4a054874bf"
          },
          {
            "name": "CPDO_LKP",
            "expression": "VAR _currentValue = COALESCE('_Measures'[Cost per Dealer Order], 0) VAR _nextValue = CALCULATE('_Measures'[Cost per Dealer Order], PARALLELPERIOD('Extract'[EST_IHD], 1, MONTH)) RETURN IF(ISBLANK(_nextValue), BLANK(), SIGN(_currentValue - _nextValue))",
            "formatString": "0",
            "lineageTag": "e3156f82-f72a-4f95-978b-bf8148dbbb23"
          },
          {
            "name": "RR_LKP",
            "expression": "VAR _currentValue = COALESCE('_Measures'[Resp. Rate], 0) VAR _nextValue = CALCULATE('_Measures'[Resp. Rate], PARALLELPERIOD('Extract'[EST_IHD], 1, MONTH)) RETURN IF(ISBLANK(_nextValue), BLANK(), SIGN(_currentValue - _nextValue))",
            "formatString": "0",
            "lineageTag": "5b9c0850-98f5-429b-a634-3cd13091377f"
          },
          {
            "name": "Dealer Cost per Dealer Order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "DIVIDE([Dealer Cost], SUM('Extract'[DealerOrders]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3677a14d-8259-4c60-8def-7b0bc8341092"
          },
          {
            "name": "Hughes Cost per Dealer Order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "DIVIDE([Hughes Cost], SUM('Extract'[DealerOrders]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a3dd484e-e6ad-443c-81d8-2a55d15515f2"
          },
          {
            "name": "Yoy_Mon",
            "expression": "VAR MaxDateInTable = CALCULATE(MAX('Extract'[EST_IHD]), ALL('Extract')) VAR CurrentDateInContext = MAX('Extract'[EST_IHD]) RETURN IF( NOT ISBLANK(CurrentDateInContext), SWITCH( TRUE(), MONTH(CurrentDateInContext) = MONTH(MaxDateInTable) && YEAR(CurrentDateInContext) = YEAR(MaxDateInTable), \"Current Month\", MONTH(CurrentDateInContext) = MONTH(MaxDateInTable) && YEAR(CurrentDateInContext) = YEAR(MaxDateInTable) - 1, \"Previous Yr\" ) )",
            "lineageTag": "76fb0c88-d6f5-4dd5-8883-9cd678e9b211"
          },
          {
            "name": "KPI_3",
            "expression": "VAR SelectedKPI = SELECTEDVALUE('KPI List 2 (copy)'[Value]) RETURN SWITCH(SelectedKPI, \"CPDO\", 0.45 * DIVIDE(SUM('Extract'[MailQTY]), SUM('Extract'[DealerOrders])), \"CPDA\", 0.45 * DIVIDE(SUM('Extract'[MailQTY]), SUM('Extract'[DealerActivations])), \"HCPDO\", [Hughes Cost per Dealer Order], \"DCPDO\", [Dealer Cost per Dealer Order], \"SAC\", (0.45 * DIVIDE(SUM('Extract'[MailQTY]), SUM('Extract'[DealerOrders]))) + 391)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c0fcd846-1834-4dc8-bc8e-11f223d4f699"
          },
          {
            "name": "Monthly / Weekly View/BDN",
            "expression": [
              "",
              "VAR SelectedView =",
              "    SELECTEDVALUE ( 'Cost Per Call Parameter'[Value] )",
              "",
              "VAR TheDate =",
              "    MAX ( 'Extract_1'[Est_IHD] )",
              "",
              "VAR TheYear =",
              "    FORMAT ( TheDate, \"YY\" )",
              "",
              "VAR TheQuarter =",
              "    \"Q\" & FORMAT ( TheDate, \"Q\" )",
              "",
              "VAR TheWeek =",
              "    \"Wk \" & FORMAT ( TheDate, \"WW\" )",
              "",
              "VAR TheMonth =",
              "    FORMAT ( TheDate, \"MMM\" )",
              "",
              "RETURN",
              "SWITCH (",
              "    SelectedView,",
              "    \"QQ\", TheQuarter & \"'\" & TheYear,",
              "    \"WW\", TheWeek & \"'\" & TheYear,",
              "    \"MM\", TheMonth & \"'\" & TheYear,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "074b73d8-f5f6-4116-aa0b-f5b6f4908ebc"
          },
          {
            "name": "Mail QTY % of Total",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM('Extract'[MailQTY]),",
              "    CALCULATE(",
              "        SUM('Extract'[MailQTY]),",
              "        REMOVEFILTERS ( 'Extract'[Mail Type Aliased] )",
              "        )",
              "    )",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "72647d80-7642-4a3d-9617-f5285a31beba"
          },
          {
            "name": "Date Range Ext1",
            "expression": [
              "",
              "VAR StartMonth =",
              "     SELECTEDVALUE ( 'Start Date (copy 2)'[Value] ) ",
              "",
              "VAR StartDate =",
              "    DATE ( YEAR ( StartMonth ), MONTH ( StartMonth ), 1 )",
              "",
              "VAR EndDate =",
              "    DATEVALUE ( SELECTEDVALUE ( 'Start Date_1 (copy)'[Value] ) )",
              "",
              "VAR CurrentDate =",
              "    MAX ( 'Extract_1'[Est_IHD] )",
              "",
              "RETURN",
              "IF (",
              "    NOT ISBLANK ( StartDate )",
              "        && NOT ISBLANK ( EndDate )",
              "        && CurrentDate >= StartDate",
              "        && CurrentDate <= EndDate,",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3455fd83-69c4-4069-9f12-bf42b76ad4b6"
          },
          {
            "name": "minest",
            "expression": "MIN(Extract_1[Est_IHD])",
            "formatString": "General Date",
            "lineageTag": "ab26776d-02b8-495c-b991-8a18dfc38318"
          },
          {
            "name": "maxest",
            "expression": "MAX(Extract_1[Est_IHD])",
            "formatString": "General Date",
            "lineageTag": "08b9ad73-e18f-481e-a4b0-501727491b84"
          },
          {
            "name": "Count Trend Indicator",
            "expression": [
              "",
              "VAR CurrentValue =",
              "    COALESCE ( [Count (copy)], 0 )",
              "",
              "VAR PreviousValue =",
              "    COALESCE (",
              "        CALCULATE (",
              "            [Count (copy)],",
              "            OFFSET (",
              "                -1,",
              "                ORDERBY ( 'Extract_1'[Est_IHD] ),",
              "                PARTITIONBY ()",
              "            )",
              "        ),",
              "        0",
              "    )",
              "",
              "VAR ChangeRatio =",
              "    DIVIDE (",
              "        CurrentValue - PreviousValue,",
              "        ABS ( PreviousValue )",
              "    )",
              "",
              "RETURN",
              "SWITCH (",
              "    TRUE(),",
              "    ChangeRatio < 0, -1,",
              "    ChangeRatio = 0,  0,",
              "    1",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f3704673-569d-445b-bc84-7e8663c8ad57"
          },
          {
            "name": "Date Range Ext",
            "expression": [
              "",
              "VAR StartMonth =",
              "     SELECTEDVALUE ( 'Start Date (copy 2)'[Value] ) ",
              "",
              "VAR StartDate =",
              "    DATE ( YEAR ( StartMonth ), MONTH ( StartMonth ), 1 )",
              "",
              "VAR EndDate =",
              "    DATEVALUE ( SELECTEDVALUE ( 'Start Date_1 (copy)'[Value] ) )",
              "",
              "VAR CurrentDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "RETURN",
              "IF (",
              "    NOT ISBLANK ( StartDate )",
              "        && NOT ISBLANK ( EndDate )",
              "        && CurrentDate >= StartDate",
              "        && CurrentDate <= EndDate,",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "852de33a-da8f-41a6-9619-e5fcea787145"
          },
          {
            "name": "Mail Count Aug-19",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count (copy)],",
              "    FILTER(",
              "        ALL('Extract_1'),",
              "        Extract_1[Est_IHD] IN {",
              "            DATE(2019, 8, 5),",
              "            DATE(2019, 8, 12)",
              "        }",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "a043a15d-94b3-46fd-8e8e-bfec88961ccd"
          },
          {
            "name": "Mail Count Previous Month",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( Extract_1[Est_IHD] )",
              "",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "RETURN",
              "CALCULATE (",
              "    [Count (copy)],",
              "    FILTER (",
              "        ALL ( Extract_1[Est_IHD] ),",
              "        Extract_1[Est_IHD] >= PrevMonthStart",
              "            && Extract_1[Est_IHD] <= PrevMonthEnd",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "27db66f2-a687-4481-b584-6c3024a7a5f6"
          },
          {
            "name": "Mail Count % Change",
            "expression": [
              "",
              "DIVIDE(",
              "    [Mail Count Aug-19] - [Mail Count Previous Month],",
              "    [Mail Count Previous Month])",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "ab6a2bda-a828-42a3-afba-6ed09079df95"
          },
          {
            "name": "Mail Count Trend Icon",
            "expression": [
              "",
              "VAR Val = [Mail Count % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")",
              ""
            ],
            "lineageTag": "98444cc5-d01e-4778-a9b5-0ec0ae00c8e9"
          },
          {
            "name": "Call Count % Change",
            "expression": [
              "",
              "VAR CallCount =",
              "    CALCULATE (",
              "        SUM ( Extract_1[Total_Calls] ),",
              "        KEEPFILTERS (",
              "            Extract_1[Est_IHD] IN {",
              "                DATE ( 2019, 8, 5 ),",
              "                DATE ( 2019, 8, 12 )",
              "            }",
              "        )",
              "    )",
              "",
              "VAR CurrentContextDate =",
              "    MAX ( Extract_1[Est_IHD] )",
              "",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "VAR Prevcount =",
              "    CALCULATE (",
              "        SUM ( Extract_1[Total_Calls] ),",
              "        FILTER (",
              "            ALL ( Extract_1 ),",
              "            Extract_1[Est_IHD] >= PrevMonthStart",
              "                && Extract_1[Est_IHD] <= PrevMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    DIVIDE (",
              "        CallCount - Prevcount,",
              "        Prevcount",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f89a4176-f5ad-4760-b572-9105cff425e7"
          },
          {
            "name": "Call Count % Change YoY",
            "expression": [
              "",
              "VAR CallCount =",
              "    CALCULATE (",
              "        SUM ( Extract_1[Total_Calls] ),",
              "        KEEPFILTERS (",
              "            Extract_1[Est_IHD] IN {",
              "                DATE ( 2019, 8, 5 ),",
              "                DATE ( 2019, 8, 12 )",
              "            }",
              "        )",
              "    )",
              "",
              "VAR CurrentContextDate =",
              "    MAX ( Extract_1[Est_IHD] )",
              "",
              "-- Same month last year (full month)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "VAR PrevYearCount =",
              "    CALCULATE (",
              "        SUM ( Extract_1[Total_Calls] ),",
              "        FILTER (",
              "            ALL ( Extract_1 ),",
              "            Extract_1[Est_IHD] >= PrevYearMonthStart",
              "                && Extract_1[Est_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearCount ),",
              "        DIVIDE ( CallCount - PrevYearCount, PrevYearCount )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "68d1f2bb-55ce-4292-a2db-f75fc5c1c414"
          },
          {
            "name": "Count % Change YoY",
            "expression": [
              "",
              "VAR CurrentCount =",
              "    CALCULATE (",
              "        [Count (copy)],",
              "        KEEPFILTERS (",
              "            Extract_1[Est_IHD] IN {",
              "                DATE ( 2019, 8, 5 ),",
              "                DATE ( 2019, 8, 12 )",
              "            }",
              "        )",
              "    )",
              "",
              "VAR CurrentContextDate =",
              "    MAX ( Extract_1[Est_IHD] )",
              "",
              "-- Same month last year (full month boundaries)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "VAR PrevYearCount =",
              "    CALCULATE (",
              "        [Count (copy)],",
              "        FILTER (",
              "            ALL ( Extract_1 ),",
              "            Extract_1[Est_IHD] >= PrevYearMonthStart",
              "                && Extract_1[Est_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearCount ),",
              "        DIVIDE ( CurrentCount - PrevYearCount, PrevYearCount )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e4e4bbfb-eb5f-4223-a974-b6c7ac5c5a5c"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "f17ba7fd-8cb5-4c27-b258-ae4002329e3b"
          },
          {
            "name": "Cost per Dealer Order % Change",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current month boundaries (derived from EST_IHD)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous month boundaries",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        [Cost per Dealer Order],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevValue =",
              "    CALCULATE (",
              "        [Cost per Dealer Order],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevValue ),",
              "        DIVIDE ( CurrentValue - PrevValue, PrevValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "7f3a7c7d-d62c-41f2-86f0-c49e60cfa861"
          },
          {
            "name": "Cost per Dealer Order % Change YoY",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current year same month (July 2019)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous year same month (July 2018)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        [Cost per Dealer Order],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevYearValue =",
              "    CALCULATE (",
              "        [Cost per Dealer Order],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevYearMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearValue ),",
              "        DIVIDE ( CurrentValue - PrevYearValue, PrevYearValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "1f8c3ea3-d173-4154-a7d9-5610c0cfb9f8"
          },
          {
            "name": "Resp. Rate % Change",
            "expression": [
              "",
              "VAR CallCount =",
              "    CALCULATE (",
              "        _Measures[Resp. Rate],",
              "        KEEPFILTERS (",
              "            Extract_1[Est_IHD] IN {",
              "                DATE ( 2019, 8, 5 ),",
              "                DATE ( 2019, 8, 12 )",
              "            }",
              "        )",
              "    )",
              "",
              "VAR CurrentContextDate =",
              "    MAX ( Extract_1[Est_IHD] )",
              "",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "VAR Prevcount =",
              "    CALCULATE (",
              "        _Measures[Resp. Rate],",
              "        FILTER (",
              "            ALL ( Extract_1 ),",
              "            Extract_1[Est_IHD] >= PrevMonthStart",
              "                && Extract_1[Est_IHD] <= PrevMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    DIVIDE (",
              "        CallCount - Prevcount,",
              "        Prevcount",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f097fe72-807f-47a6-b61c-925fbefff829"
          },
          {
            "name": "Resp. Rate % Change YoY",
            "expression": [
              "",
              "VAR CallCount =",
              "    CALCULATE (",
              "        _Measures[Resp. Rate],",
              "        KEEPFILTERS (",
              "            Extract_1[Est_IHD] IN {",
              "                DATE ( 2019, 8, 5 ),",
              "                DATE ( 2019, 8, 12 )",
              "            }",
              "        )",
              "    )",
              "",
              "VAR CurrentContextDate =",
              "    MAX ( Extract_1[Est_IHD] )",
              "",
              "-- Same month last year (full month)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "VAR PrevYearCount =",
              "    CALCULATE (",
              "        _Measures[Resp. Rate],",
              "        FILTER (",
              "            ALL ( Extract_1 ),",
              "            Extract_1[Est_IHD] >= PrevYearMonthStart",
              "                && Extract_1[Est_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearCount ),",
              "        DIVIDE ( CallCount - PrevYearCount, PrevYearCount )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "9e2e5e35-ec1e-40df-92fa-4505beecb944"
          },
          {
            "name": "Order Rate % Change",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current month boundaries (derived from EST_IHD)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous month boundaries",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        [Order Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevValue =",
              "    CALCULATE (",
              "        [Order Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevValue ),",
              "        DIVIDE ( CurrentValue - PrevValue, PrevValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "907f8734-5c91-4661-8b2c-bab3636e46de"
          },
          {
            "name": "Order Rate % Change YoY",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current year same month (July 2019)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous year same month (July 2018)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        [Order Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevYearValue =",
              "    CALCULATE (",
              "        [Order Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevYearMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearValue ),",
              "        DIVIDE ( CurrentValue - PrevYearValue, PrevYearValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "1f2a8e53-42f4-4ece-9c60-a89b3f405a97"
          },
          {
            "name": "Activation Rate % Change",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current month boundaries (derived from EST_IHD)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous month boundaries",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        [Activation Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevValue =",
              "    CALCULATE (",
              "        [Activation Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevValue ),",
              "        DIVIDE ( CurrentValue - PrevValue, PrevValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "963a3b9e-6b90-4f74-9de8-f5bf0e422c9e"
          },
          {
            "name": "Activation Rate % Change YoY",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current year same month (July 2019)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous year same month (July 2018)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        [Activation Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevYearValue =",
              "    CALCULATE (",
              "        [Activation Rate],",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevYearMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearValue ),",
              "        DIVIDE ( CurrentValue - PrevYearValue, PrevYearValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6948f13d-f821-4368-803b-ca79c675b895"
          },
          {
            "name": "Dealer Orders % Change",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current month boundaries (derived from EST_IHD)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous month boundaries",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerOrders]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerOrders]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevValue ),",
              "        DIVIDE ( CurrentValue - PrevValue, PrevValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "4c1fc7c5-b529-49d0-983e-7742cf40854b"
          },
          {
            "name": "Dealer Orders % Change YoY",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current year same month (July 2019)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous year same month (July 2018)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerOrders]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevYearValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerOrders]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevYearMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearValue ),",
              "        DIVIDE ( CurrentValue - PrevYearValue, PrevYearValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "5e73a4c5-62d6-4b28-b841-8aaf022977a2"
          },
          {
            "name": "Dealer Activations % Change",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current month boundaries (derived from EST_IHD)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous month boundaries",
              "VAR PrevMonthStart =",
              "    EOMONTH ( CurrentContextDate, -2 ) + 1",
              "",
              "VAR PrevMonthEnd =",
              "    EOMONTH ( CurrentContextDate, -1 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerActivations]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerActivations]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevValue ),",
              "        DIVIDE ( CurrentValue - PrevValue, PrevValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "42fb85c2-aa06-4b1a-bca6-02b5e40d70f9"
          },
          {
            "name": "Dealer Activations % Change YoY",
            "expression": [
              "",
              "VAR CurrentContextDate =",
              "    MAX ( 'Extract'[EST_IHD] )",
              "",
              "-- Current year same month (July 2019)",
              "VAR CurrentMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ),",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR CurrentMonthEnd =",
              "    EOMONTH ( CurrentContextDate, 0 )",
              "",
              "-- Previous year same month (July 2018)",
              "VAR PrevYearMonthStart =",
              "    DATE (",
              "        YEAR ( CurrentContextDate ) - 1,",
              "        MONTH ( CurrentContextDate ),",
              "        1",
              "    )",
              "",
              "VAR PrevYearMonthEnd =",
              "    EOMONTH ( PrevYearMonthStart, 0 )",
              "",
              "-- Values",
              "VAR CurrentValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerActivations]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= CurrentMonthStart",
              "                && 'Extract'[EST_IHD] <= CurrentMonthEnd",
              "        )",
              "    )",
              "",
              "VAR PrevYearValue =",
              "    CALCULATE (",
              "        sum('Extract'[DealerActivations]),",
              "        FILTER (",
              "            ALL ( 'Extract' ),",
              "            'Extract'[EST_IHD] >= PrevYearMonthStart",
              "                && 'Extract'[EST_IHD] <= PrevYearMonthEnd",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( PrevYearValue ),",
              "        DIVIDE ( CurrentValue - PrevYearValue, PrevYearValue )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "9da54c61-12e3-4247-90ca-e29b4d53e09b"
          },
          {
            "name": "Mail Count Shape Color",
            "expression": [
              "",
              "VAR v = [Mail Count % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "8ba8412f-bc23-4667-a81e-35bb2d6215f4"
          },
          {
            "name": "Count Trend Icon",
            "expression": [
              "",
              "VAR Val = [Count % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "c9c635a3-dcb3-4b8a-9b6f-37ddcfba0d6a"
          },
          {
            "name": "Count Shape Color",
            "expression": [
              "",
              "VAR v = [Count % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "321defb3-5487-46b3-ac19-a9f4032553c9"
          },
          {
            "name": "Cost Dealer Order Icon",
            "expression": [
              "",
              "VAR Val = [Cost per Dealer Order % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "693344e5-c4df-4b8d-a67f-1bea3e0616b4"
          },
          {
            "name": "Cost Dealer Order Color",
            "expression": [
              "",
              "VAR v = [Cost per Dealer Order % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "66f1aabf-acef-43b0-941f-5c6facde83cb"
          },
          {
            "name": "Cost Dealer YoY Icon",
            "expression": [
              "",
              "VAR Val = [Cost per Dealer Order % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "54cdaacc-3019-4b13-95ba-60dcefbe1b1a"
          },
          {
            "name": "Cost Dealer YoY Color",
            "expression": [
              "",
              "VAR v = [Cost per Dealer Order % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "d27bc231-1e08-4377-a6bd-b81ec3e8a6d3"
          },
          {
            "name": "Call Count Trend Icon",
            "expression": [
              "",
              "VAR Val = [Call Count % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")",
              ""
            ],
            "lineageTag": "c217ab34-3e59-4e61-8621-470abf6f3e40"
          },
          {
            "name": "Call Count Color",
            "expression": [
              "",
              "VAR v = [Call Count % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "ce257508-324b-4815-99b4-cf1c942f323f"
          },
          {
            "name": "Call Count YoY Icon",
            "expression": [
              "",
              "VAR Val = [Call Count % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "37d519d0-4ca4-4fe1-a4dc-0ba01acd4e60"
          },
          {
            "name": "Call Count YoY Color",
            "expression": [
              "",
              "VAR v = [Call Count % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "faf9c2ac-7425-4c8f-bbc0-3a7e1956f544"
          },
          {
            "name": "Dealer Order Trend Icon",
            "expression": [
              "",
              "VAR Val = [Dealer Orders % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "1b46dd19-d583-4561-a198-737931762fbc"
          },
          {
            "name": "Dealer Order Color",
            "expression": [
              "",
              "VAR v = [Dealer Orders % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "c9b84dd5-ef91-4066-a1fc-129a7a10e79a"
          },
          {
            "name": "Dealer Order YoY Icon",
            "expression": [
              "",
              "VAR Val = [Dealer Orders % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "c95bc272-9bd5-4e67-ac3d-e8bb5a678e57"
          },
          {
            "name": "Dealer Order YoY Color",
            "expression": [
              "",
              "VAR v = [Dealer Orders % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "26a0ae69-4f78-46d9-9e74-4d7a22ae930d"
          },
          {
            "name": "Dealer Activations Icon",
            "expression": [
              "",
              "VAR Val = [Dealer Activations % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "c7b8bb55-9b80-4a59-bf50-da894d3eb9aa"
          },
          {
            "name": "Dealer Activations Color",
            "expression": [
              "",
              "VAR v = [Dealer Activations % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "087e9c3c-3d9e-4bd5-9a64-c6fd1ea0dce2"
          },
          {
            "name": "Dealer Activations YoY Icon",
            "expression": [
              "",
              "VAR Val = [Dealer Activations % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "eab97973-b62b-49db-881d-46224fadc22a"
          },
          {
            "name": "Dealer Activations YoY Color",
            "expression": [
              "",
              "VAR v = [Dealer Activations % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "45ad5dab-5760-44c5-979b-28a818f58729"
          },
          {
            "name": "Resp. Rate Icon",
            "expression": [
              "",
              "VAR Val = [Resp. Rate % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")",
              ""
            ],
            "lineageTag": "72892dd6-f884-454f-9dac-9fbc010dc881"
          },
          {
            "name": "Resp. Rate Color",
            "expression": [
              "",
              "VAR v = _Measures[Resp. Rate % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "4555d31f-edc0-4cfa-adfd-b445a71517ab"
          },
          {
            "name": "Resp. Rate YoY Icon",
            "expression": [
              "",
              "VAR Val = [Resp. Rate % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "a0ff2fbe-792e-4a0c-a4d4-8bd2ce1db8b2"
          },
          {
            "name": "Resp. Rate YoY Color",
            "expression": [
              "",
              "VAR v = [Resp. Rate % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "8582e1e9-c4ca-48a3-b100-bd8c0e138c43"
          },
          {
            "name": "Order Rate Icon",
            "expression": [
              "",
              "VAR Val = [Order Rate % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "07888fa8-600b-4a0b-b9c9-41b31f1b58e2"
          },
          {
            "name": "Order Rate Color",
            "expression": [
              "",
              "VAR v = [Order Rate % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "f7eb4c97-39c5-4059-b9be-31af6288e827"
          },
          {
            "name": "Order Rate YoY Color",
            "expression": [
              "",
              "VAR v = [Order Rate % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")"
            ],
            "lineageTag": "0cd7c5d0-f0ca-47f6-bcdc-4bd0d2bb777c"
          },
          {
            "name": "Order Rate YoY Icon",
            "expression": [
              "",
              "VAR Val = [Order Rate % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "43d6de42-b815-45ab-9c4a-1db6b156620a"
          },
          {
            "name": "Activation Rate Icon",
            "expression": [
              "",
              "VAR Val = [Activation Rate % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "02496970-f34e-4498-94bf-890902d9d2e2"
          },
          {
            "name": "Activation Rate Color",
            "expression": [
              "",
              "VAR v = [Activation Rate % Change]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "95e28daa-dd40-4bf6-9e33-8b3fd65b17fd"
          },
          {
            "name": "Activation Rate YoY Icon",
            "expression": [
              "",
              "VAR Val = [Activation Rate % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(Val), BLANK(),",
              "    Val > 0, UNICHAR(9650),   -- ▲ Up filled triangle",
              "    Val < 0, UNICHAR(9660),   -- ▼ Down filled triangle",
              "    UNICHAR(8212)               -- — Neutral",
              ")"
            ],
            "lineageTag": "75d9a2ee-db9a-49f2-9a86-ee56c22c160a"
          },
          {
            "name": "Activations Rate YoY Color",
            "expression": [
              "",
              "VAR v = [Activation Rate % Change YoY]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(v), \"#9E9E9E\",   -- Grey",
              "    v > 0, \"#2E7D32\",        -- Green",
              "    v < 0, \"#C62828\",        -- Red",
              "    \"#9E9E9E\"",
              ")",
              ""
            ],
            "lineageTag": "7459b9bb-a3c1-43a7-91c0-f5cba874e8c4"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table(type table [_Dummy = Int64.Type], {{1}})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_78f5f87b-4487-4113-a43d-1f53dd9492ef",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b7115830-eaac-4a1a-9865-cb63ff5ba317",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9bbdcea3-49f0-4c31-bda0-3602079db6ca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "349b7242-ec8d-434b-94dc-0aac611e2483",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4843e672-17e6-4540-a923-53e52d16eb60",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0bc31b7d-1a2a-49c8-898c-ac51a318aa78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "db39ffe2-3655-4d9d-8969-d19ae473917b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8652548b-0a91-4c65-ab56-777b456a318c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b30009b1-02ff-4d55-bcb4-09a93fe241b2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ca44bc04-88f3-4cd5-b33e-f53d63805d05",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2d1b5ecb-a80d-4cb2-afb3-be0a56034dee",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "184adaa6-15fa-4fb6-900c-e13be21b49ba",
                "ordinal": 3
              }
            ],
            "lineageTag": "183d4e13-e879-4441-85af-4b96ecc41382"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a1475542-e292-4087-9d99-aacb5866a3b3",
        "partitions": [
          {
            "name": "DateTableTemplate_78f5f87b-4487-4113-a43d-1f53dd9492ef",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_733e3aeb-49ed-4803-b3d6-3ff1b5f1fa76",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "56134a0d-dc8b-4fc8-ad7c-1dbbc5972354",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c327db9f-d8aa-4f2d-aaac-e322ef11ada9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bf0818f2-eb73-4f91-b4a8-4c20c7791c5b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "42ebac02-256e-41b6-8b7d-6c38ae4911a3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a9b29f5b-5128-4a01-a340-e749e95badbe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "777c73ae-c729-4404-97f8-88eb5c3fd970",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d186cfae-91c7-4d97-b921-c2c449e2728e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d3acfbb1-8178-4ecb-a671-ba874bf94559",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c8f7b321-1f1b-4869-ac8d-fe9eebacc068",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c96b16bf-ee3a-438e-a7e0-aef96dfedaa5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fb176b34-a215-4b9d-bfe7-45b68cf9447b",
                "ordinal": 3
              }
            ],
            "lineageTag": "ce8d39ef-08d3-4baf-8caa-298adc3b0a71"
          }
        ],
        "isHidden": true,
        "lineageTag": "e5c1ecba-35d5-4a4a-995e-c2468c83e745",
        "partitions": [
          {
            "name": "LocalDateTable_733e3aeb-49ed-4803-b3d6-3ff1b5f1fa76",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Extract_1'[Est_IHD])), 1, 1), Date(Year(MAX('Extract_1'[Est_IHD])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_39312de2-7a2b-47d3-9374-89a175986186",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "09d51b6f-8640-484b-9c24-bf34c1a847b0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4f3ca0a8-c041-4c3c-aa98-9912d9a99a3d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea86ccb8-cd37-4652-9ab5-73fd0456f873",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "01ddde1f-0f79-4004-a767-1e127f5dfa9f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "49a74b98-6423-4252-9139-9d9ef9f11c41",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7478870f-d0c5-4159-8a10-0ac81d913a41",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fa12421e-a576-452a-99ac-735ffc67bc09",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b3d275b3-d0ee-46eb-bdc4-6d8e546dcc6b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0a19f32e-d8cc-41d4-b2a0-8711d2e6f916",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f94d96d7-27f9-4b31-abf1-e798fedadf69",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d23bca49-3150-41e9-bc59-8c2a9532fd94",
                "ordinal": 3
              }
            ],
            "lineageTag": "a7e01822-037b-40c6-bc31-0df238510c41"
          }
        ],
        "isHidden": true,
        "lineageTag": "cac0b9d5-6446-4f41-8f5b-8a57f5919466",
        "partitions": [
          {
            "name": "LocalDateTable_39312de2-7a2b-47d3-9374-89a175986186",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Extract_1'[Est IHD (copy)])), 1, 1), Date(Year(MAX('Extract_1'[Est IHD (copy)])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_10a12dba-9d3a-446a-b254-a5797d834c22",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ab7fe73e-e72a-4bd0-9ee3-2a289a0f0b30",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "edc45007-f7e1-4186-b703-929204a17ab6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6b468dd9-c34e-4e6a-9bd2-f1bec23a1172",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2015f49f-9263-4456-b97e-9982992742ff",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b021b51d-53b5-475f-a94c-e356d109b558",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ceeac941-80e9-438c-a134-f68eccaec489",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8c97a85-c7b3-48e1-9579-e11ab818836f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "dd16a21b-272c-4984-8762-79a68c0d91a1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fd6c21f1-3a02-4009-8077-f55e2e590d2c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5c574027-afd2-45bb-a01b-7a729af1d80b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "39406e28-e980-42e7-bea8-46207b98a96b",
                "ordinal": 3
              }
            ],
            "lineageTag": "4c82f80d-7f6d-4792-a8f2-b626f4c9d1c0"
          }
        ],
        "isHidden": true,
        "lineageTag": "fe9e68b7-029a-479e-a665-735e2383c362",
        "partitions": [
          {
            "name": "LocalDateTable_10a12dba-9d3a-446a-b254-a5797d834c22",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Extract'[EST_IHD])), 1, 1), Date(Year(MAX('Extract'[EST_IHD])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Month/Weekly Param",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d159a80c14a547cfb1c60356003f8ca3"
          }
        ],
        "columns": [
          {
            "name": "Month/Weekly Param",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "0ab2c8d1-6d63-413f-b1a6-941e02551fe2",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Month/Weekly Param Fields"
                }
              ]
            },
            "sortByColumn": "Month/Weekly Param Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month/Weekly Param Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7ba3a406-52e5-4e33-83b1-a56f3e50fbf3",
            "sortByColumn": "Month/Weekly Param Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month/Weekly Param Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "919b4687-86ce-4506-8edc-802b1512716e",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4d6990ac-e92b-499e-a409-be6cbfb5b9e0",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d0eb2620-c693-4bbd-a024-31229a5728d9",
        "partitions": [
          {
            "name": "Month/Weekly Param",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Monthly\", NAMEOF('Extract_1'[Mon_yr]), 0, \"MM\"),",
                "    (\"Weekly\", NAMEOF('Extract_1'[Week_yr]), 1, \"WW\"),",
                "    (\"Quarterly\", NAMEOF('Extract_1'[Qtr_yr]), 2, \"QQ\"),",
                "    (\"Yearly\", NAMEOF('Extract_1'[Year]), 3, \"YY\")",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "month/week kpi-2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "38b809c9adab430194120cab33f33d7f"
          }
        ],
        "columns": [
          {
            "name": "month/week kpi-2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "e802a6ab-735a-470c-ac04-a3d01d992057",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "month/week kpi-2 Fields"
                }
              ]
            },
            "sortByColumn": "month/week kpi-2 Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "month/week kpi-2 Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0fea9cf7-3cfb-46c7-8049-bf3047d60a71",
            "sortByColumn": "month/week kpi-2 Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "month/week kpi-2 Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5d8cc6cc-fa47-43a0-a3c6-c9910e976f49",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "cd09a7d4-6fbf-4cf8-b6a9-0747e74be7fb",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c409831f-0a00-4714-874c-06ae95a36300",
        "partitions": [
          {
            "name": "month/week kpi-2",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Monthly\", NAMEOF('Extract'[Mon_yr]), 0, \"MM\"),",
                "    (\"Weekly\", NAMEOF('Extract'[Week_yr]), 1, \"WW\"),",
                "    (\"Quarterly\", NAMEOF('Extract'[Qtr_yr]), 2, \"QQ\"),",
                "    (\"Yearly\", NAMEOF('Extract'[Year]), 3, \"YY\")",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}